import Appointment from "../models/Appointment.js";
import Doctor from "../models/Doctor.js";
import TokenCase from "../models/TokenCase.js";

// =====================================================
// HELPER: FIND DOCTOR FROM IDENTIFIER
// =====================================================

const findDoctorByIdentifier = async (identifier) => {
  if (!identifier?.trim()) {
    return null;
  }

  const normalizedIdentifier = identifier.trim();

  return await Doctor.findOne({
    $or: [
      { mobile: normalizedIdentifier },
      { email: normalizedIdentifier.toLowerCase() },
      { regNumber: normalizedIdentifier },
    ],
  });
};

// =====================================================
// HELPER: GET DOCTOR IDENTIFIER
// =====================================================

const getDoctorIdentifier = (req) => {
  return (
    req.query.identifier ||
    req.query.doctorIdentifier ||
    req.body?.identifier ||
    req.headers["x-doctor-identifier"] ||
    ""
  );
};

// =====================================================
// 1. CREATE CASE / APPOINTMENT REQUEST
// Patient submits Case Taking form
// =====================================================

export const createAppointment = async (req, res) => {
  try {
    const patientId = req.user.id;

    const { crNumber, tokenNumber, hospitalName, department, reason, consent } =
      req.body;

    // ---------------------------------------------
    // Validate required fields
    // ---------------------------------------------

    if (!crNumber?.trim()) {
      return res.status(400).json({
        success: false,
        message: "CR number is required.",
      });
    }

    if (!tokenNumber?.trim() || !hospitalName?.trim() || !department?.trim()) {
      return res.status(400).json({
        success: false,
        message: "Token number, hospital/clinic, and department are required.",
      });
    }

    // ---------------------------------------------
    // Validate data consent
    // ---------------------------------------------

    if (consent !== true) {
      return res.status(400).json({
        success: false,
        message: "Data sharing consent is required before submitting the case.",
      });
    }

    // ---------------------------------------------
    // Find doctor
    // ---------------------------------------------

    const doctor = await Doctor.findOne({
      hospitalClinic: hospitalName.trim(),
      department: department.trim(),
    });

    if (!doctor) {
      return res.status(404).json({
        success: false,
        message:
          "No doctor found for the selected hospital/clinic and department.",
      });
    }

    // ---------------------------------------------
    // Prevent duplicate active case
    // ---------------------------------------------

    const existingAppointment = await Appointment.findOne({
      patientId,
      tokenNumber: tokenNumber.trim(),
      hospitalName: hospitalName.trim(),
      department: department.trim(),
      status: {
        $in: ["Pending", "Accepted"],
      },
    });

    if (existingAppointment) {
      return res.status(400).json({
        success: false,
        message: "You already have an active case request for this token.",
      });
    }

    // ---------------------------------------------
    // Automatically store request date/time
    // ---------------------------------------------

    const requestDate = new Date();

    const requestTime = requestDate.toLocaleTimeString("en-IN", {
      hour: "2-digit",
      minute: "2-digit",
      hour12: true,
    });

    // ---------------------------------------------
    // Create TokenCase
    // ---------------------------------------------
    //
    // IMPORTANT:
    // CR number comes from the patient.
    // It is NOT generated by the backend.
    // ---------------------------------------------

    const tokenCase = await TokenCase.create({
      patientId,

      doctorId: doctor._id,

      hospitalName: hospitalName.trim(),

      department: department.trim(),

      tokenNumber: tokenNumber.trim(),

      crNumber: crNumber.trim(),

      // Patient gave consent during Case Taking
      dataConsent: {
        status: "Confirmed",
        confirmedAt: requestDate,
        sharedItems: ["Patient Details", "AI Summary", "Medical Reports"],
      },

      doctorAction: "Pending",

      summaryStatus: "AI summary Not available",
    });

    try {
      // ---------------------------------------------
      // Create Appointment / Case Request
      // ---------------------------------------------

      const appointment = await Appointment.create({
        patientId,

        doctorId: doctor._id,

        tokenCaseId: tokenCase._id,

        tokenNumber: tokenNumber.trim(),

        hospitalName: hospitalName.trim(),

        department: department.trim(),

        // Automatically stored request information
        requestDate,

        requestTime,

        // Consultation information will be added
        // when doctor accepts the case
        appointmentDate: null,

        appointmentTime: null,

        reason: reason?.trim() || "",

        status: "Pending",
      });

      return res.status(201).json({
        success: true,

        message: "Case submitted successfully.",

        appointment,

        case: {
          crNumber: tokenCase.crNumber,
          tokenNumber: tokenCase.tokenNumber,
          hospitalName: tokenCase.hospitalName,
          department: tokenCase.department,
        },

        request: {
          requestDate,

          requestTime,
        },
      });
    } catch (appointmentError) {
      // If Appointment creation fails,
      // remove TokenCase.
      await TokenCase.findByIdAndDelete(tokenCase._id);

      throw appointmentError;
    }
  } catch (error) {
    console.error("Create case request error:", error);

    return res.status(500).json({
      success: false,

      message: "Failed to submit case request.",

      error: error.message,
    });
  }
};

// =====================================================
// 2. GET ALL APPOINTMENTS ASSIGNED TO DOCTOR
// =====================================================

export const getDoctorAppointments = async (req, res) => {
  try {
    const doctorIdentifier = getDoctorIdentifier(req);

    if (!doctorIdentifier) {
      return res.status(400).json({
        success: false,
        message: "Doctor identifier is required.",
      });
    }

    // ---------------------------------------------
    // Find doctor
    // ---------------------------------------------

    const doctor = await findDoctorByIdentifier(doctorIdentifier);

    if (!doctor) {
      return res.status(404).json({
        success: false,
        message: "Doctor not found.",
      });
    }

    // ---------------------------------------------
    // Get doctor's appointments
    // ---------------------------------------------

    const appointments = await Appointment.find({
      doctorId: doctor._id,
    })
      .populate("patientId", "fullName mobile email dob gender abhaId")
      .populate(
        "tokenCaseId",
        "tokenNumber hospitalName department summaryStatus dataConsent doctorAction crNumber aiSummary",
      )
      .sort({
        status: 1,
        requestDate: -1,
        createdAt: -1,
      });

    return res.status(200).json({
      success: true,

      totalAppointments: appointments.length,

      appointments,

      todayAppointments: appointments,
    });
  } catch (error) {
    console.error("Get doctor appointments error:", error);

    return res.status(500).json({
      success: false,

      message: "Failed to fetch doctor appointments.",

      error: error.message,
    });
  }
};

// =====================================================
// 2A. GET DOCTOR CASE DETAILS
// Doctor views patient + AI summary
// =====================================================

export const getDoctorCaseDetails = async (req, res) => {
  try {
    const { appointmentId } = req.params;

    const doctorIdentifier = getDoctorIdentifier(req);

    // ---------------------------------------------
    // Validate doctor identifier
    // ---------------------------------------------

    if (!doctorIdentifier?.trim()) {
      return res.status(400).json({
        success: false,
        message: "Doctor identifier is required.",
      });
    }

    // ---------------------------------------------
    // Find doctor
    // ---------------------------------------------

    const doctor = await findDoctorByIdentifier(doctorIdentifier);

    if (!doctor) {
      return res.status(404).json({
        success: false,
        message: "Doctor not found.",
      });
    }

    // ---------------------------------------------
    // Find appointment assigned to this doctor
    // ---------------------------------------------

    const appointment = await Appointment.findOne({
      _id: appointmentId,
      doctorId: doctor._id,
    })
      .populate("patientId", "fullName mobile email dob gender abhaId")
      .populate(
        "tokenCaseId",
        "tokenNumber hospitalName department crNumber summaryStatus aiSummary aiSummaryStatus patientApproved approvedForDoctorSharing patientReviewNote doctorEditedSummary doctorEditedAt doctorEditedBy summarySource",
      );

    if (!appointment) {
      return res.status(404).json({
        success: false,
        message: "Appointment/case not found for this doctor.",
      });
    }

    return res.status(200).json({
      success: true,

      appointment,

      patient: appointment.patientId,

      case: appointment.tokenCaseId,

      // ---------------------------------------------
      // Summary information
      // ---------------------------------------------

      summary: {
        aiSummary: appointment.tokenCaseId?.aiSummary?.fullSummary || "",

        doctorEditedSummary: appointment.tokenCaseId?.doctorEditedSummary || "",

        summarySource: appointment.tokenCaseId?.summarySource || "AI",

        doctorEditedAt: appointment.tokenCaseId?.doctorEditedAt || null,

        doctorEditedBy: appointment.tokenCaseId?.doctorEditedBy || null,
      },
    });
  } catch (error) {
    console.error("Get doctor case details error:", error);

    return res.status(500).json({
      success: false,
      message: "Failed to fetch doctor case details.",
      error: error.message,
    });
  }
};

// =====================================================
// 2B. SAVE DOCTOR-EDITED FINAL SUMMARY
// =====================================================

export const updateDoctorEditedSummary = async (req, res) => {
  try {
    const { appointmentId } = req.params;

    const { identifier, doctorEditedSummary } = req.body;

    // ---------------------------------------------
    // Validate doctor identifier
    // ---------------------------------------------

    if (!identifier?.trim()) {
      return res.status(400).json({
        success: false,
        message: "Doctor identifier is required.",
      });
    }

    // ---------------------------------------------
    // Validate summary
    // ---------------------------------------------

    if (
      typeof doctorEditedSummary !== "string" ||
      !doctorEditedSummary.trim()
    ) {
      return res.status(400).json({
        success: false,
        message: "Doctor-edited summary cannot be empty.",
      });
    }

    // ---------------------------------------------
    // Find doctor
    // ---------------------------------------------

    const doctor = await findDoctorByIdentifier(identifier);

    if (!doctor) {
      return res.status(404).json({
        success: false,
        message: "Doctor not found.",
      });
    }

    // ---------------------------------------------
    // Find appointment belonging to doctor
    // ---------------------------------------------

    const appointment = await Appointment.findOne({
      _id: appointmentId,
      doctorId: doctor._id,
    });

    if (!appointment) {
      return res.status(404).json({
        success: false,
        message: "Appointment/case not found for this doctor.",
      });
    }

    // ---------------------------------------------
    // Find linked TokenCase
    // ---------------------------------------------

    if (!appointment.tokenCaseId) {
      return res.status(404).json({
        success: false,
        message: "No case is linked to this appointment.",
      });
    }

    const tokenCase = await TokenCase.findOne({
      _id: appointment.tokenCaseId,
      doctorId: doctor._id,
    });

    if (!tokenCase) {
      return res.status(404).json({
        success: false,
        message: "Case not found for this doctor.",
      });
    }

    // ---------------------------------------------
    // SAVE COMPLETE FINAL SUMMARY
    // ---------------------------------------------

    tokenCase.doctorEditedSummary = doctorEditedSummary.trim();

    tokenCase.doctorEditedAt = new Date();

    tokenCase.doctorEditedBy = doctor._id;

    tokenCase.summarySource = "DoctorEdited";

    await tokenCase.save();

    return res.status(200).json({
      success: true,

      message: "Doctor-edited summary saved successfully.",

      summary: {
        aiSummary: tokenCase.aiSummary.fullSummary,

        doctorEditedSummary: tokenCase.doctorEditedSummary,

        summarySource: tokenCase.summarySource,

        doctorEditedAt: tokenCase.doctorEditedAt,

        doctorEditedBy: tokenCase.doctorEditedBy,
      },
    });
  } catch (error) {
    console.error("Update doctor-edited summary error:", error);

    return res.status(500).json({
      success: false,

      message: "Failed to save doctor-edited summary.",

      error: error.message,
    });
  }
};

// =====================================================
// 3. ACCEPT APPOINTMENT
// Doctor selects ONLY consultation time
// =====================================================

export const acceptAppointment = async (req, res) => {
  try {
    const { appointmentId } = req.params;

    const { identifier, appointmentTime } = req.body;

    // ---------------------------------------------
    // Validate doctor identifier
    // ---------------------------------------------

    if (!identifier?.trim()) {
      return res.status(400).json({
        success: false,
        message: "Doctor identifier is required.",
      });
    }

    // ---------------------------------------------
    // Validate consultation time
    // ---------------------------------------------

    if (!appointmentTime?.trim()) {
      return res.status(400).json({
        success: false,
        message: "Consultation time is required.",
      });
    }

    // ---------------------------------------------
    // Find doctor
    // ---------------------------------------------

    const doctor = await findDoctorByIdentifier(identifier);

    if (!doctor) {
      return res.status(404).json({
        success: false,
        message: "Doctor not found.",
      });
    }

    // ---------------------------------------------
    // Find pending appointment
    // ---------------------------------------------

    const appointment = await Appointment.findOne({
      _id: appointmentId,

      doctorId: doctor._id,

      status: "Pending",
    });

    if (!appointment) {
      return res.status(404).json({
        success: false,
        message: "Pending case request not found.",
      });
    }

    // ---------------------------------------------
    // Consultation date
    // Automatically set to today's date.
    // Doctor only chooses the time.
    // ---------------------------------------------

    const appointmentDate = new Date();

    appointmentDate.setHours(0, 0, 0, 0);

    // ---------------------------------------------
    // Check time conflict
    // ---------------------------------------------

    const conflictingAppointment = await Appointment.findOne({
      _id: {
        $ne: appointmentId,
      },

      doctorId: doctor._id,

      status: "Accepted",

      appointmentDate,

      appointmentTime: appointmentTime.trim(),
    });

    if (conflictingAppointment) {
      return res.status(409).json({
        success: false,

        message:
          "The doctor already has an appointment at this consultation time.",
      });
    }

    // ---------------------------------------------
    // Accept appointment
    // ---------------------------------------------

    appointment.status = "Accepted";

    appointment.appointmentDate = appointmentDate;

    appointment.appointmentTime = appointmentTime.trim();

    await appointment.save();

    // ---------------------------------------------
    // Update TokenCase
    // ---------------------------------------------

    if (appointment.tokenCaseId) {
      await TokenCase.findByIdAndUpdate(
        appointment.tokenCaseId,

        {
          doctorId: doctor._id,

          doctorAction: "Accepted",
        },

        {
          returnDocument: "after",
        },
      );
    }

    return res.status(200).json({
      success: true,

      message: "Appointment accepted successfully.",

      appointment,
    });
  } catch (error) {
    console.error("Accept appointment error:", error);

    return res.status(500).json({
      success: false,

      message: "Failed to accept appointment.",

      error: error.message,
    });
  }
};

// =====================================================
// 4. DOCTOR REJECTS CASE REQUEST
// =====================================================

export const rejectAppointment = async (req, res) => {
  try {
    const { appointmentId } = req.params;

    const { identifier } = req.body;

    // ---------------------------------------------
    // Validate identifier
    // ---------------------------------------------

    if (!identifier?.trim()) {
      return res.status(400).json({
        success: false,

        message: "Doctor identifier is required.",
      });
    }

    // ---------------------------------------------
    // Find doctor
    // ---------------------------------------------

    const doctor = await findDoctorByIdentifier(identifier);

    if (!doctor) {
      return res.status(404).json({
        success: false,

        message: "Doctor not found.",
      });
    }

    // ---------------------------------------------
    // Find pending appointment
    // ---------------------------------------------

    const appointment = await Appointment.findOne({
      _id: appointmentId,

      doctorId: doctor._id,

      status: "Pending",
    });

    if (!appointment) {
      return res.status(404).json({
        success: false,

        message: "Pending case request not found.",
      });
    }

    // ---------------------------------------------
    // Reject appointment
    // ---------------------------------------------

    appointment.status = "Rejected";

    await appointment.save();

    // ---------------------------------------------
    // Update TokenCase
    // ---------------------------------------------

    if (appointment.tokenCaseId) {
      await TokenCase.findByIdAndUpdate(
        appointment.tokenCaseId,

        {
          doctorId: doctor._id,

          doctorAction: "Rejected",
        },

        {
          returnDocument: "after",
        },
      );
    }

    return res.status(200).json({
      success: true,

      message: "Case request rejected successfully.",

      appointment,
    });
  } catch (error) {
    console.error("Reject appointment error:", error);

    return res.status(500).json({
      success: false,

      message: "Failed to reject case request.",

      error: error.message,
    });
  }
};

// =====================================================
// 5. GET ALL APPOINTMENTS OF LOGGED-IN PATIENT
// =====================================================

export const getPatientAppointments = async (req, res) => {
  try {
    const patientId = req.user.id;

    const appointments = await Appointment.find({
      patientId,
    })
      .populate(
        "doctorId",
        "fullName specialization hospitalClinic department degree regNumber",
      )
      .populate(
        "tokenCaseId",
        "tokenNumber hospitalName department summaryStatus dataConsent doctorAction crNumber aiSummary",
      )
      .sort({
        appointmentDate: -1,

        requestDate: -1,

        createdAt: -1,
      });

    return res.status(200).json({
      success: true,

      totalAppointments: appointments.length,

      appointments,
    });
  } catch (error) {
    console.error("Get patient appointments error:", error);

    return res.status(500).json({
      success: false,

      message: "Failed to fetch appointments.",

      error: error.message,
    });
  }
};

// =====================================================
// 6. GET SINGLE APPOINTMENT
// =====================================================

export const getAppointmentById = async (req, res) => {
  try {
    const patientId = req.user.id;

    const { appointmentId } = req.params;

    const appointment = await Appointment.findOne({
      _id: appointmentId,

      patientId,
    })
      .populate(
        "doctorId",
        "fullName specialization hospitalClinic department degree regNumber",
      )
      .populate(
        "tokenCaseId",
        "tokenNumber hospitalName department summaryStatus doctorAction crNumber aiSummary",
      );

    if (!appointment) {
      return res.status(404).json({
        success: false,

        message: "Appointment not found.",
      });
    }

    return res.status(200).json({
      success: true,

      appointment,
    });
  } catch (error) {
    console.error("Get appointment error:", error);

    return res.status(500).json({
      success: false,

      message: "Failed to fetch appointment.",

      error: error.message,
    });
  }
};

// =====================================================
// 7. CANCEL APPOINTMENT
// =====================================================

export const cancelAppointment = async (req, res) => {
  try {
    const patientId = req.user.id;

    const { appointmentId } = req.params;

    const appointment = await Appointment.findOne({
      _id: appointmentId,

      patientId,
    });

    if (!appointment) {
      return res.status(404).json({
        success: false,

        message: "Appointment not found.",
      });
    }

    // ---------------------------------------------
    // Completed appointments cannot be cancelled
    // ---------------------------------------------

    if (appointment.status === "Completed") {
      return res.status(400).json({
        success: false,

        message: "Completed appointments cannot be cancelled.",
      });
    }

    // ---------------------------------------------
    // Cancel
    // ---------------------------------------------

    appointment.status = "Cancelled";

    await appointment.save();

    return res.status(200).json({
      success: true,

      message: "Appointment cancelled successfully.",

      appointment,
    });
  } catch (error) {
    console.error("Cancel appointment error:", error);

    return res.status(500).json({
      success: false,

      message: "Failed to cancel appointment.",

      error: error.message,
    });
  }
};
