import express from "express";

import {
  createAppointment,
  getPatientAppointments,
  getDoctorAppointments,
  getDoctorCaseDetails,
  updateDoctorEditedSummary,
  acceptAppointment,
  rejectAppointment,
  getAppointmentById,
  cancelAppointment,
} from "../controllers/appointmentController.js";

import { verifyToken } from "../middleware/auth.js";

const router = express.Router();

// =====================================================
// PATIENT ROUTES
// =====================================================

// Create case / appointment request
// Patient provides:
// - Token Number
// - Hospital / Clinic
// - Department
// - Data Consent
//
// Request date and request time are automatically
// generated by the backend.
router.post("/", verifyToken, createAppointment);

// Get logged-in patient's appointments
router.get("/my-appointments", verifyToken, getPatientAppointments);

// =====================================================
// DOCTOR ROUTES
// =====================================================

// Get all case requests assigned to doctor
router.get("/doctor-appointments", getDoctorAppointments);

router.get("/doctor-case/:appointmentId", getDoctorCaseDetails);

router.put("/doctor-case/:appointmentId/summary", updateDoctorEditedSummary);

// Doctor accepts case request
// Doctor provides ONLY consultation time.
// Consultation date is automatically handled
// by the backend.
router.put("/:appointmentId/accept", acceptAppointment);

// Doctor rejects case request
router.put("/:appointmentId/reject", rejectAppointment);

// =====================================================
// GENERAL APPOINTMENT ROUTES
// =====================================================

// Get single appointment
router.get("/:appointmentId", verifyToken, getAppointmentById);

// Cancel patient's appointment
router.put("/:appointmentId/cancel", verifyToken, cancelAppointment);

export default router;
